environment: production
chdir: /var/www/apps/sudokill/current/
address: 127.0.0.1
user: ross
group: users
port: 8000
pid: /var/www/apps/sudokill/current/tmp/thin.pid
rackup: /var/www/apps/sudokill/current/config.ru
log: /var/www/apps/sudokill/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true