--- 
production: 
  instances: 2
  port: 
    websocket: 46544
    http: 
    socket: 44444
  host: 0.0.0.0
  max_time: 
    websocket: 600
    socket: 120
development: 
  instances: 2
  port: 
    websocket: 8080
    http: 4567
    socket: 4444
  host: 0.0.0.0
  max_time: 
    websocket: 600
    socket: 120
