#! /usr/bin/env ruby

require 'socket'

class Chat

  def initialize(tag, host = 'localhost', port = 44444)
    @tag = tag
    TCPSocket.open(host, port) do |server|
    puts server.gets.chomp

    loop do
      input = STDIN.gets
      server.puts input
      server.flush
      puts server.gets.chomp

      break if input.chomp =~ /bye/i
    end

    end
  end

end

raise "Usage: ruby script/chat [name] [host:optional] [port:optional]" if ARGV.length == 0
name = ARGV.shift
host = ARGV.shift
port = ARGV.shift
Chat.new(name, host, port)