#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib/"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'sudokoup'

name = ARGV.shift
host = ARGV.shift
port = ARGV.shift

client = Sudokoup::Client.start({
  :name => name,
  :host => host,
  :port => port
})

client.call(client.name)
log client.read

loop do
  input = STDIN.gets
  client.call(input)
  log client.read
end