#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib/"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'sudokl'

host = (ARGV.shift || '127.0.0.1')
port = (ARGV.shift || 45454)
socket = (ARGV.shift || 8080)

module Dummy
  def post_init
    send_data "GET /\r\n\r\n"
  end

  def receive_data(data)
    puts data
  end
end

EM.run do

  trap("TERM") { Sudokl::WebSocket.stop }
  trap("INT")  { Sudokl::WebSocket.stop }

  @proxy = EM.connect host, port, Sudokl::Proxy

  Sudokl::WebSocket.start(:host => "0.0.0.0", :port => socket, :debug => true) do |ws|

    ws.onopen    {
      @proxy.websocket = ws
    }

    ws.onmessage { |msg|
      # @proxy.send_data(msg)
    }

    ws.onclose   {
      ws.send "Closing time"
      puts "WebSocket closed"
    }

  end

end