#! /usr/bin/env ruby

require 'yaml'

config = {
  "development" => {
    "instances" => 2,
    "host" => "0.0.0.0",
    "port" => {
      "socket" => 4444,
      "websocket" => 8080,
      "http" => 4567
    }
  },
  "production" => {
    "instances" => 4,
    "host" => "0.0.0.0",
    "port" => {
      "socket" => 44444,
      "websocket" => 48080,
      "http" => 45678
    }
  }
}

File.open( 'config/server.yml', 'w' ) do |out|
   YAML.dump(config, out)
end