#! /usr/bin/env ruby

require 'rubygems'
require 'socket'

class EchoServer

  def initialize(host, port)
    @host = host || '127.0.0.1'
    @port = port || 55555
    
    begin
      @server = TCPServer.new(@host, @port)
    rescue Exception => e
      puts e.message
    end
  end

  def connect
    puts "Waiting for client on port #{@port}"
    client = @server.accept
    client.puts "Welcome"
    puts client.readline
    while message = STDIN.gets
      client.puts message
      puts client.readline
    end
    client.close
  end
end

host = ARGV.shift
port = ARGV.shift
server  = EchoServer.new(host, port)
server.connect
