#! /usr/bin/env ruby

# lib_path = File.expand_path(File.dirname(__FILE__)) + "/.."
# $LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'socket'

class EchoServer

  def initialize(port)
    @port = port
    begin
      @server = TCPServer.new('127.0.0.1', @port)
    rescue Exception => e
      puts e.message
    end
  end

  def connect
    puts "Waiting for client on port #{@port}"
    client = @server.accept
    client.puts "Welcome"
    puts client.readline
    while message = STDIN.gets
      client.puts message
      puts client.readline
    end
    client.close
  end
end

server  = EchoServer.new(5555)
server.connect
