#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib/"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path

require 'sudocoup'

host      = ARGV.shift || '0.0.0.0'
port      = ARGV.shift || 44444
ws_port   = ARGV.shift || 8080
http_port = ARGV.shift || 45678

if ENV["LOG"]
  log = "log/sudocoup.log"
  file = File.open(log, "a")
  Sudocoup::Logger.logger = Logger.new(log)
end

if ENV['WEB']
  system "LOG=1 script/web #{host} #{http_port} #{ws_port} &"
end

Sudocoup::Server.start(
  :host => host,
  :port => port,
  :ws_port => ws_port,
  :size => 2
)
