#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib/"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'sudokoup'

host = ARGV.shift
port = ARGV.shift
sock = ARGV.shift

controller = Sudokoup::Controller.new({
  :host => host,
  :port => port,
  :sock => sock
})

controller.connect!