#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib/"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path

require "rubygems"
require 'sudokill/web_server'

host      = ARGV.shift || '0.0.0.0'
ws_port   = ARGV.shift || 8080
http_port = ARGV.shift || 4567

if ENV["LOG"]
  log = File.new("log/sinatra.log", "a+")
  log.sync = true
  STDOUT.reopen(log)
  STDERR.reopen(log)
end

# ruby lib/sudokill/web_server.rb [-h] [-x] [-e production] [-o linserv1.cims.nyu.edu] [-p 45678] [-s HANDLER]
Sudokill::WebServer.run!(:bind => host, :port => http_port, :ws_port => ws_port)